/** English dictionary — UI keys. */
export const dict: Record<string, string> = {
  // Common
  "umum.mulai_gratis": "Start free",
  "umum.masuk": "Sign in",
  "umum.daftar": "Sign up",
  "umum.keluar": "Sign out",
  "umum.simpan": "Save",
  "umum.batal": "Cancel",
  "umum.hapus": "Delete",
  "umum.ubah": "Change",
  "umum.tutup": "Close",
  "umum.kembali": "Back",
  "umum.muat_ulang": "Reload",
  "umum.menyalin": "Copying…",
  "umum.tersalin": "Copied",
  "umum.berhasil": "Success",
  "umum.gagal": "Failed",
  "umum.memuat": "Loading…",
  "umum.menghitung_estimasi": "Estimating…",
  "umum.estimasi_selesai": "About {waktu} remaining",
  "umum.proses_berjalan_server": "Processing runs on the server — you can close this page; clips appear automatically when done.",

  // Navigation
  "nav.dashboard": "Dashboard",
  "nav.proyek": "Projects",
  "nav.unduh": "Downloads",
  "nav.admin": "Admin",
  "nav.pengaturan": "Settings",
  "nav.bantuan": "Help",

  // Dashboard
  "dash.judul": "Dashboard",
  "dash.sambutan": "Welcome back, {nama}",
  "dash.buat_baru": "Create a new video",
  "dash.proyek_terbaru": "Recent projects",
  "dash.belum_ada_proyek": "No projects yet — paste a YouTube link to start.",
  "dash.klip": "Clips",
  "dash.durasi": "Duration",
  "dash.skor_rerata": "Avg. score",
  "dash.analisis_ai": "AI analysis",
  "dash.lihat_semua": "View all",

  // Project
  "proyek.kembali": "All projects",
  "proyek.klip_terdeteksi": "Detected clips",
  "proyek.belum_ada": "none yet",
  "proyek.tahap_ambil": "Fetch media",
  "proyek.tahap_transkripsi": "Transcription",
  "proyek.tahap_pilih_momen": "Pick moments",
  "proyek.tahap_selesai": "Done",
  "proyek.sumber_youtube": "YouTube source",
  "proyek.sumber_unggahan": "Uploaded video",

  // Downloads
  "unduh.judul": "Rendered videos",
  "unduh.belum_ada": "No rendered videos yet.",
  "unduh.unduh": "Download",
  "unduh.putar": "Play",
  "unduh.selesai": "Done",
  "unduh.memproses": "Processing",

  // Editor
  "editor.kembali": "Back",
  "editor.unduh": "Download",
  "editor.subtitel": "Subtitle",
  "editor.deskripsi": "Description",
  "editor.ikon": "Icons",
  "editor.gaya_subtitel": "Subtitle styles",
  "editor.ukuran": "Size",
  "editor.memproses_video": "Processing video",
  "editor.mengambil_potongan": "Fetching source clips…",
  "editor.hapus_watermark": "Remove watermark",
  "editor.auto_split": "Auto split",
  "editor.preview_belum": "Preview not available yet.",
  "editor.jeda": "Pause",
  "editor.putar": "Play",
  "editor.garis_waktu": "Clip timeline",
  "editor.berjalan": "Running {waktu}",
  "editor.render_terhenti": "Render stalled — reload the page",
  "editor.melanjutkan_render": "Resuming render…",
  "editor.gagal_memulai": "Failed to start — try reloading the page",

  // Settings
  "set.judul": "Settings",
  "set.profil": "Profile",
  "set.foto_profil": "Profile photo",
  "set.unggah_foto": "Upload photo",
  "set.username": "Username",
  "set.username_bantuan": "Shown on public pages and clip attribution.",
  "set.email": "Email",
  "set.ganti_sandi": "Change password",
  "set.sandi_baru": "New password",
  "set.sandi_konfirmasi": "Repeat new password",
  "set.sandi_tidak_sama": "The two passwords don't match.",
  "set.sandi_pendek": "Password must be at least 8 characters.",
  "set.sandi_berhasil": "Password changed.",
  "set.sandi_salah": "Password change failed — check and try again.",
  "set.bahasa": "Language",
  "set.bahasa_bantuan": "All interface text uses this language. Clip subtitles follow the video.",
  "set.tersimpan": "Changes saved.",
  "set.terdeteksi_browser": "Detected from your browser: {bahasa}",

  // Auth
  "auth.selamat_datang": "Welcome back",
  "auth.buat_akun": "Create account",
  "auth.email": "Email",
  "auth.sandi": "Password",
  "auth.nama_tampilan": "Display name",
  "auth.lupa_sandi": "Forgot password?",
  "auth.masuk_sekarang": "Sign in now",
  "auth.kode_verifikasi": "Enter verification code",
  "auth.kode_kirim_ke": "We sent 6 digits to {email}. Your account can't be used until the code is entered.",
  "auth.kode_placeholder": "000000",
  "auth.kode_bantuan": "The code is valid for 1 hour. Check spam if it hasn't arrived.",
  "auth.verifikasi_masuk": "Verify & sign in",
  "auth.memverifikasi": "Verifying…",
  "auth.kirim_ulang": "Resend code",
  "auth.kirim_ulang_hitung": "Resend code ({detik}s)",
  "auth.kembali_masuk": "Back to sign in",
  "auth.kode_salah": "Code is wrong or expired. Request a new one.",
};
