/** Kamus bahasa Indonesia — sumber kebenaran kunci UI. */
export const dict: Record<string, string> = {
  // Umum
  "umum.mulai_gratis": "Mulai gratis",
  "umum.masuk": "Masuk",
  "umum.daftar": "Daftar",
  "umum.keluar": "Keluar",
  "umum.simpan": "Simpan",
  "umum.batal": "Batal",
  "umum.hapus": "Hapus",
  "umum.ubah": "Ubah",
  "umum.tutup": "Tutup",
  "umum.kembali": "Kembali",
  "umum.muat_ulang": "Muat ulang",
  "umum.menyalin": "Menyalin…",
  "umum.tersalin": "Tersalin",
  "umum.berhasil": "Berhasil",
  "umum.gagal": "Gagal",
  "umum.memuat": "Memuat…",
  "umum.menghitung_estimasi": "Menghitung estimasi…",
  "umum.estimasi_selesai": "Estimasi selesai ~{waktu} lagi",
  "umum.proses_berjalan_server": "Proses berjalan di server — halaman boleh ditutup, klip muncul otomatis saat selesai.",

  // Navigasi & halaman
  "nav.dashboard": "Dashboard",
  "nav.proyek": "Proyek",
  "nav.unduh": "Unduhan",
  "nav.admin": "Admin",
  "nav.pengaturan": "Pengaturan",
  "nav.bantuan": "Bantuan",

  // Dashboard
  "dash.judul": "Dashboard",
  "dash.sambutan": "Selamat datang kembali, {nama}",
  "dash.buat_baru": "Buat video baru",
  "dash.proyek_terbaru": "Proyek terbaru",
  "dash.belum_ada_proyek": "Belum ada proyek — tempel link YouTube untuk memulai.",
  "dash.klip": "Klip",
  "dash.durasi": "Durasi",
  "dash.skor_rerata": "Skor rerata",
  "dash.analisis_ai": "Analisis AI",
  "dash.lihat_semua": "Lihat semua",

  // Proyek
  "proyek.kembali": "Semua proyek",
  "proyek.klip_terdeteksi": "Klip terdeteksi",
  "proyek.belum_ada": "belum ada",
  "proyek.tahap_ambil": "Ambil media",
  "proyek.tahap_transkripsi": "Transkripsi",
  "proyek.tahap_pilih_momen": "Pilih momen",
  "proyek.tahap_selesai": "Selesai",
  "proyek.sumber_youtube": "Sumber YouTube",
  "proyek.sumber_unggahan": "Video unggahan",

  // Unduh
  "unduh.judul": "Hasil render",
  "unduh.belum_ada": "Belum ada video yang dirender.",
  "unduh.unduh": "Unduh",
  "unduh.putar": "Putar",
  "unduh.selesai": "Selesai",
  "unduh.memproses": "Memproses",

  // Editor
  "editor.kembali": "Kembali",
  "editor.unduh": "Unduh",
  "editor.subtitel": "Subtitle",
  "editor.deskripsi": "Deskripsi",
  "editor.ikon": "Ikon",
  "editor.gaya_subtitel": "Gaya subtitle",
  "editor.ukuran": "Ukuran",
  "editor.memproses_video": "Sedang memproses video",
  "editor.mengambil_potongan": "Mengambil potongan sumber…",
  "editor.hapus_watermark": "Hapus watermark",
  "editor.auto_split": "Auto split",
  "editor.preview_belum": "Preview belum tersedia.",
  "editor.jeda": "Jeda",
  "editor.putar": "Putar",
  "editor.garis_waktu": "Garis waktu klip",
  "editor.berjalan": "Berjalan {waktu}",
  "editor.render_terhenti": "Render terhenti — tekan muat ulang halaman",
  "editor.melanjutkan_render": "Melanjutkan render…",
  "editor.gagal_memulai": "Gagal memulai — coba muat ulang halaman",

  // Pengaturan
  "set.judul": "Pengaturan",
  "set.profil": "Profil",
  "set.foto_profil": "Foto profil",
  "set.unggah_foto": "Unggah foto",
  "set.username": "Nama pengguna",
  "set.username_bantuan": "Tampil di halaman publik dan atribusi klip.",
  "set.email": "Email",
  "set.ganti_sandi": "Ganti kata sandi",
  "set.sandi_baru": "Kata sandi baru",
  "set.sandi_konfirmasi": "Ulangi kata sandi baru",
  "set.sandi_tidak_sama": "Kedua kata sandi belum sama.",
  "set.sandi_pendek": "Kata sandi minimal 8 karakter.",
  "set.sandi_berhasil": "Kata sandi diganti.",
  "set.sandi_salah": "Ganti kata sandi gagal — periksa lagi.",
  "set.bahasa": "Bahasa",
  "set.bahasa_bantuan": "Semua teks antarmuka memakai bahasa ini. Subtitle klip mengikuti video.",
  "set.tersimpan": "Perubahan disimpan.",
  "set.terdeteksi_browser": "Terdeteksi dari bahasa browser: {bahasa}",

  // Auth
  "auth.selamat_datang": "Selamat datang kembali",
  "auth.buat_akun": "Buat akun",
  "auth.email": "Email",
  "auth.sandi": "Kata sandi",
  "auth.nama_tampilan": "Nama tampilan",
  "auth.lupa_sandi": "Lupa kata sandi?",
  "auth.masuk_sekarang": "Masuk sekarang",
  "auth.kode_verifikasi": "Masukkan kode verifikasi",
  "auth.kode_kirim_ke": "Kami mengirim 6 angka ke {email}. Akun belum bisa dipakai sebelum kode ini dimasukkan.",
  "auth.kode_placeholder": "000000",
  "auth.kode_bantuan": "Kode berlaku 1 jam. Periksa folder spam kalau belum masuk.",
  "auth.verifikasi_masuk": "Verifikasi & masuk",
  "auth.memverifikasi": "Memverifikasi…",
  "auth.kirim_ulang": "Kirim ulang kode",
  "auth.kirim_ulang_hitung": "Kirim ulang kode ({detik}s)",
  "auth.kembali_masuk": "Kembali ke halaman masuk",
  "auth.kode_salah": "Kode salah atau sudah kedaluwarsa. Minta kode baru.",
  "auth.masuk_untuk_lanjut": "Masuk untuk lanjut mengubah video jadi klip.",
  "auth.gratis_tanpa_kartu": "Gratis, tanpa kartu kredit.",
  "auth.kode_dikirim": "Kode verifikasi dikirim ke email kamu.",
  "auth.email_belum_verif": "Email belum diverifikasi. Masukkan kode dari email kamu.",
  "auth.kode_baru_dikirim": "Kode baru dikirim. Cek email kamu.",
};
