"""FFmpeg render engine — burns the SAME ASS file the browser preview uses.

Parity guarantee (user requirement: preview == MP4 result):
  preview  : browser canvas renders words+style with rules mirroring libass
  render   : ffmpeg -vf ass=captions.ass on a 1080x1920 canvas
The ASS file is generated by app/subtitles.py from the same CaptionStyle JSON
the frontend sends, so parameters cannot drift between preview and result.

Face tracking (port sederhana dari OpenShorts TRACK mode):
  - Analisis pass di Python: sampling frame tiap N frame di resolusi rendah,
    deteksi posisi "subject" via deteksi gerak + deteksi wajah sederhana
    (gradient-based Viola-Jones via OpenCV kalau tersedia; fallback: centroid
    gerak). Kamera virtual smooth (safe-zone + pan speed) seperti
    SmoothedCameraman OpenShorts.
  - Render pass: crop dinamis via ffmpeg sendcmd + crop filter.
"""

from __future__ import annotations

import os
import json
import shutil
import subprocess
import tempfile
from typing import Any, Optional

import numpy as np
import cv2
import mediapipe as mp

ASPECT = 9 / 16
ANALYSIS_WIDTH = 320          # low-res analysis pass
DETECT_STRIDE = 5             # analyze every Nth frame
SAFE_ZONE_FRACTION = 0.22
PAN_SPEED_FAST = 18.0
PAN_SPEED_SLOW = 4.0

# MediaPipe BlazeFace setup (OpenShorts style) - legacy API (mediapipe 0.10)
mp_face_detection = mp.solutions.face_detection
_face_detector = mp_face_detection.FaceDetection(model_selection=1, min_detection_confidence=0.5)


def run_ffmpeg(cmd: list[str], *, timeout: int | None = None, nice: int = 10):
    """Jalankan ffmpeg dengan prioritas RENDAH (nice+ionice).

    Tanpa ini ffmpeg menyita CPU/IO → web server ikut lag & halaman blank
    beberapa detik saat user menekan Unduh. nice=10 + ionice best-effort 7
    membuat kernel selalu mengutamakan proses web/API.
    """
    prefix: list[str] = []
    if shutil.which("nice"):
        prefix += ["nice", "-n", str(nice)]
    if shutil.which("ionice"):
        prefix += ["ionice", "-c", "2", "-n", "7"]
    kwargs: dict[str, Any] = {"check": True, "capture_output": True}
    if timeout:
        kwargs["timeout"] = timeout
    return subprocess.run(prefix + cmd, **kwargs)


def probe_duration(path: str) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "json", path],
        capture_output=True, text=True, check=True,
    ).stdout
    return float(json.loads(out)["format"]["duration"])


def render_preview(
    src: str,
    start: float,
    end: float,
    out_path: str,
    width: int = 360,
    height: int = 640,
    max_seconds: float = 12.0,
) -> str:
    """Fitur-nya kecil + super cepat (VPS, ditanggung server).

    Bikin klip preview resolusi rendah (360x640) tanpa burn karaoke —
    cukup potong + crop 9:16 + transkode cepat. Dipakai browser supaya
    preview editor muncul INSTAN (file kecil, bukan stream 43MB sumber).
    Durasi di-cap (max_seconds) supaya render cepat & file kecil.
    """
    duration = min(end - start, max_seconds)
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=width,height", "-of", "json", src],
        capture_output=True, text=True,
    )
    src_w, src_h = 1080, 1920
    if probe.returncode == 0:
        try:
            d = json.loads(probe.stdout)["streams"][0]
            src_w, src_h = int(d["width"]), int(d["height"])
        except Exception:
            pass

    aspect = width / height
    # center crop to 9:16
    if src_w / src_h > aspect:
        vf = f"crop=w={int(src_h * aspect)}:h={src_h}:x=(iw-ow)/2:y=0,scale={width}:{height}"
    else:
        vf = f"crop=w={src_w}:h={int(src_w / aspect)}:x=0:y=(ih-oh)/2,scale={width}:{height}"

    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{duration:.3f}", "-i", src,
        "-vf", vf,
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "26",
        "-pix_fmt", "yuv420p",
        "-an",
        "-movflags", "+faststart",
        out_path,
    ]
    run_ffmpeg(cmd)
    return out_path


def probe_size(path: str) -> tuple[int, int]:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=width,height", "-of", "json", path],
        capture_output=True, text=True, check=True,
    ).stdout
    data = json.loads(out)["streams"][0]
    return int(data["width"]), int(data["height"])


# ---------------------------------------------------------------------------
# Camera trajectory (SmoothedCameraman port)
# ---------------------------------------------------------------------------

def smooth_camera(
    current: float, target: float, crop_width: float, video_width: float,
    fast: float = PAN_SPEED_FAST, slow: float = PAN_SPEED_SLOW,
) -> float:
    diff = target - current
    safe = crop_width * SAFE_ZONE_FRACTION
    if abs(diff) <= safe:
        return current
    direction = 1.0 if diff > 0 else -1.0
    speed = fast if abs(diff) > crop_width * 0.5 else slow
    new = current + direction * speed
    half = crop_width / 2
    new = max(half, min(video_width - half, new))
    new_diff = target - new
    if (direction == 1 and new_diff < 0) or (direction == -1 and new_diff > 0):
        new = target
    return new


def analyze_speaker_track(src: str, start: float, end: float) -> dict[str, Any]:
    """Trajektori kamera MULTI-ORANG: sorot orang yang SEDANG BICARA.

    Cara kerja (tanpa model tambahan):
    1. MediaPipe BlazeFace mendeteksi SEMUA wajah tiap frame (5 fps).
    2. Deteksi dikelompokkan jadi 'track' per orang (jarak antar-frame).
    3. Aktivitas bicara diukur dari GERAK MULUT: selisih piksel di area
       keypoint mulut antar frame (EMA, jadi kebal noise 1 frame).
    4. Kamera hanya berpindah kalau orang lain dominan bicara selama
       >=0.6 detik (histeresis) — mencegah kamera bolak-balik.

    Return {"trajectory": [...], "faces": n_max, "switches": n}.
    Kalau hanya 1 orang → perilaku sama seperti face tracking biasa.
    """
    import numpy as np

    try:
        w, h = probe_size(src)
    except Exception:
        return {"trajectory": [], "faces": 0, "switches": 0}
    dur = min(end - start, 180)
    analysis_h = max(180, int(ANALYSIS_WIDTH * h / w / 2) * 2)
    analysis_w = int(analysis_h * w / h / 2) * 2
    fps = 5
    cmd = [
        "ffmpeg", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{dur:.3f}", "-i", src,
        "-vf", f"scale={analysis_w}:{analysis_h}",
        "-r", str(fps),
        "-f", "rawvideo", "-pix_fmt", "rgb24", "-",
    ]
    try:
        raw = run_ffmpeg(cmd, timeout=900).stdout
    except Exception:
        return {"trajectory": [], "faces": 0, "switches": 0}
    frame_bytes = analysis_w * analysis_h * 3
    n_frames = len(raw) // frame_bytes
    if n_frames < 4:
        return {"trajectory": [], "faces": 0, "switches": 0}
    frames = np.frombuffer(raw[: n_frames * frame_bytes], dtype=np.uint8).reshape(
        n_frames, analysis_h, analysis_w, 3
    )

    MATCH_DIST = analysis_w * 0.16      # jarak maks dianggap orang yang sama
    SWITCH_FRAMES = 3                   # 3 frame @5fps = 0.6s dominan berturut
    SWITCH_RATIO = 1.8                  # kandidat harus jelas lebih aktif
    EMA = 0.55                          # (dipakai sbg cadangan; lihat EMA asimetris)
    MIN_MOTION = 2.0                    # ambang absolut "sedang bicara"
    QUIET_MOTION = 1.6                  # di bawah ini dianggap BERHENTI bicara
    CUT_COOLDOWN = int(fps * 1.5)       # jeda minimal antar potong (1.5s)

    tracks: list[dict[str, Any]] = []
    retired: list[dict[str, Any]] = []      # track hilang sesaat (wajah ketutup mic)
    active_idx: int | None = None
    active_uid: list[int | None] = [None]   # uid orang yang sedang disorot
    _next_uid = [1]
    last_cut = [-999]                       # frame potong terakhir (cooldown)
    MIN_CUT_DIST = analysis_w * 0.10         # potong hanya kalau posisi beda nyata
    pending_idx: int | None = None
    pending_count = 0
    switches = 0
    max_faces = 0
    targets: list[float] = []
    cut_frames: set[int] = set()      # frame di mana pembicara BERGANTI → potong keras

    for fi in range(n_frames):
        frame = frames[fi]
        gray = frame.mean(axis=2)
        res = _face_detector.process(frame)
        dets = list(res.detections or [])
        max_faces = max(max_faces, len(dets))

        seen: set[int] = set()
        for d in dets:
            bb = d.location_data.relative_bounding_box
            cx = (bb.xmin + bb.width / 2) * analysis_w
            cy = (bb.ymin + bb.height / 2) * analysis_h
            # keypoint mulut (index 3) → fallback ke bawah bbox
            try:
                kp = d.location_data.relative_keypoints[3]
                mx, my = kp.x * analysis_w, kp.y * analysis_h
            except Exception:
                mx, my = cx, (bb.ymin + bb.height * 0.80) * analysis_h
            r = max(4, int(bb.width * analysis_w * 0.22))
            y0, y1 = max(0, int(my - r)), min(analysis_h, int(my + r))
            x0, x1 = max(0, int(mx - r)), min(analysis_w, int(mx + r))
            patch = gray[y0:y1, x0:x1]

            # cocokkan ke track terdekat
            best_i, best_d = None, 1e9
            for i, tr in enumerate(tracks):
                if i in seen:
                    continue
                dist = abs(tr["cx"] - cx) + abs(tr["cy"] - cy) * 0.5
                if dist < best_d:
                    best_i, best_d = i, dist
            if best_i is not None and best_d <= MATCH_DIST:
                tr = tracks[best_i]
                prev = tr.get("patch")
                motion = 0.0
                if (prev is not None and prev.shape == patch.shape
                        and patch.size > 0):
                    motion = float(np.abs(patch.astype(np.float32)
                                          - prev.astype(np.float32)).mean())
                # EMA asimetris: NAIK cepat (mulai bicara langsung terdeteksi),
                # TURUN lebih lambat (jeda antar kata tidak dianggap berhenti)
                a = 0.75 if motion > tr["motion"] else 0.35
                tr["motion"] = tr["motion"] * (1 - a) + motion * a
                tr["cx"], tr["cy"] = cx, cy
                tr["patch"] = patch
                tr["last"] = fi
                seen.add(best_i)
            else:
                # SEBELUM membuat identitas baru: cek track yang baru hilang
                # (wajah ketutup mic/tangan lalu muncul lagi). Tanpa ini,
                # orang yang sama dapat uid baru → dianggap ganti pembicara →
                # kamera memotong padahal tidak ada pergantian.
                reuse = None
                for rt in retired:
                    if fi - rt["last"] > fps * 4:
                        continue
                    if abs(rt["cx"] - cx) + abs(rt["cy"] - cy) * 0.5 <= MATCH_DIST * 1.6:
                        reuse = rt
                        break
                if reuse is not None:
                    retired.remove(reuse)
                    reuse.update({"cx": cx, "cy": cy, "patch": patch,
                                  "last": fi})
                    tracks.append(reuse)
                else:
                    tracks.append({"cx": cx, "cy": cy, "patch": patch,
                                   "motion": 0.0, "last": fi,
                                   "uid": _next_uid[0]})
                    _next_uid[0] += 1
                seen.add(len(tracks) - 1)

        # buang track yang lama hilang (>2s) — simpan sebentar di `retired`
        # supaya identitasnya bisa dipakai lagi kalau wajahnya muncul kembali
        stale = [t for t in tracks if fi - t["last"] > fps * 2]
        if stale:
            retired.extend(stale)
            retired = [t for t in retired if fi - t["last"] <= fps * 6][-8:]
        tracks = [t for t in tracks if fi - t["last"] <= fps * 2]
        live = [t for t in tracks if fi - t["last"] <= 1]

        prev_uid = active_uid[0]

        if not live:
            targets.append(targets[-1] if targets else analysis_w / 2)
            continue
        if len(live) == 1:
            active_idx = tracks.index(live[0])
            prev_cx = targets[-1] if targets else live[0]["cx"]
            active_uid[0] = live[0]["uid"]
            # potong HANYA kalau benar-benar orang lain DAN posisinya beda
            # nyata; kalau tidak, biarkan pan halus (mis. wajah sempat hilang).
            # MIN_CUT_DIST digandakan di sini: 1 wajah terlihat = paling sering
            # cuma deteksi kedip-kedip, bukan pergantian pembicara sungguhan.
            if (prev_uid is not None and prev_uid != active_uid[0]
                    and abs(live[0]["cx"] - prev_cx) >= MIN_CUT_DIST * 2.0
                    and fi - last_cut[0] >= CUT_COOLDOWN):
                cut_frames.add(fi)          # orang berganti → teleport
                last_cut[0] = fi
                switches += 1
            targets.append(live[0]["cx"])
            continue

        # >1 orang: pilih yang mulutnya paling aktif
        loud = max(live, key=lambda t: t["motion"])
        cur = None
        if active_uid[0] is not None:
            cur = next((t for t in live if t["uid"] == active_uid[0]), None)
        if cur is None:
            active_idx = tracks.index(loud)
            prev_cx = targets[-1] if targets else loud["cx"]
            active_uid[0] = loud["uid"]
            if (prev_uid is not None and prev_uid != active_uid[0]
                    and abs(loud["cx"] - prev_cx) >= MIN_CUT_DIST
                    and fi - last_cut[0] >= CUT_COOLDOWN):
                cut_frames.add(fi)
                last_cut[0] = fi
                switches += 1
            pending_idx, pending_count = None, 0
        elif (loud is not cur
              and loud["motion"] >= MIN_MOTION
              and loud["motion"] > cur["motion"] * SWITCH_RATIO
              # yang sedang disorot harus benar-benar BERHENTI bicara —
              # tanpa syarat ini kamera pindah saat dua-duanya bicara
              and cur["motion"] < QUIET_MOTION):
            li = tracks.index(loud)
            if pending_idx == li:
                pending_count += 1
            else:
                pending_idx, pending_count = li, 1
            # cooldown: jangan potong bolak-balik lebih cepat dari 1.2s
            if (pending_count >= SWITCH_FRAMES
                    and fi - last_cut[0] >= CUT_COOLDOWN
                    and abs(loud["cx"] - cur["cx"]) >= MIN_CUT_DIST):
                active_idx = li
                active_uid[0] = loud["uid"]
                cut_frames.add(fi)          # PINDAH PEMBICARA → potong keras
                last_cut[0] = fi
                switches += 1
                pending_idx, pending_count = None, 0
        else:
            pending_idx, pending_count = None, 0

        at = None
        if active_uid[0] is not None:
            at = next((t for t in live if t["uid"] == active_uid[0]), None)
        at = at or loud
        targets.append(at["cx"])

    # Trajektori kamera:
    #  - orang SAMA bergerak  → ikuti wajah HALUS & TERPUSAT
    #  - GANTI pembicara      → teleport (cam langsung ke posisi orang baru)
    #
    # Trajektori dihitung OFFLINE (seluruh klip sudah dianalisis), jadi tidak
    # perlu filter kausal seperti EMA — EMA selalu tertinggal di belakang wajah
    # ("miring dari wajahnya") dan kalau dipercepat jadi patah-patah.
    # Di sini dipakai penghalusan ZERO-PHASE (maju-mundur) per SEGMEN antar
    # potongan: hasilnya mulus TANPA lag, tetap terpusat di wajah, dan
    # teleport di titik cut tetap tajam karena tiap segmen dihaluskan sendiri.
    scale = w / analysis_w
    crop_w = min(int(h * ASPECT), w)
    half = crop_w / 2

    def _median3(seq: list[float]) -> list[float]:
        """Buang jitter deteksi 1 frame."""
        if len(seq) < 3:
            return list(seq)
        out = [seq[0]]
        for i in range(1, len(seq) - 1):
            out.append(sorted(seq[i - 1:i + 2])[1])
        out.append(seq[-1])
        return out

    def _smooth_zero_phase(seq: list[float], win: int) -> list[float]:
        """Rata-rata bergerak dua arah (maju lalu mundur) = tanpa pergeseran fase."""
        if len(seq) < 3 or win < 2:
            return list(seq)
        k = min(win, max(2, len(seq) // 2))
        cur = list(seq)
        for _ in range(2):                      # 2 lintasan = kurva makin halus
            # maju
            acc = cur[0]
            fwd = []
            a_ = 2.0 / (k + 1)
            for v in cur:
                acc += (v - acc) * a_
                fwd.append(acc)
            # mundur (mengembalikan lag yang ditimbulkan lintasan maju)
            acc = fwd[-1]
            bwd = [0.0] * len(fwd)
            for i in range(len(fwd) - 1, -1, -1):
                acc += (fwd[i] - acc) * a_
                bwd[i] = acc
            cur = bwd
        return cur

    # segmen = potongan trajektori antara dua cut (teleport tidak dihaluskan)
    bounds = [0] + sorted(c for c in cut_frames if 0 < c < len(targets)) + [len(targets)]
    SMOOTH_WIN = max(3, int(fps * 0.9))      # jendela ±0.9 detik
    traj_analysis: list[float] = []
    for b0, b1 in zip(bounds, bounds[1:]):
        seg = targets[b0:b1]
        if not seg:
            continue
        seg = _median3(seg)
        seg = _smooth_zero_phase(seg, SMOOTH_WIN)
        traj_analysis.extend(seg)

    trajectory: list[float] = []
    for tc in traj_analysis:
        cam_x = max(half, min(w - half, tc * scale))
        trajectory.append(cam_x)
    return {"trajectory": trajectory, "faces": max_faces,
            "switches": switches, "cuts": sorted(cut_frames),
            "analysis_fps": fps}


def analyze_face_track(src: str, start: float, end: float) -> list[float]:
    """Trajektori kamera (kompatibel lama) — kini memakai speaker tracking."""
    return analyze_speaker_track(src, start, end)["trajectory"]


def _analyze_face_track_single(src: str, start: float, end: float) -> list[float]:
    """Versi lama: selalu ikut wajah TERBESAR (dipakai sebagai cadangan)."""
    import numpy as np
    try:
        w, h = probe_size(src)
    except Exception:
        return []
    dur = min(end - start, 120)  # cap analysis length
    analysis_h = max(180, int(ANALYSIS_WIDTH * h / w / 2) * 2)
    analysis_w = int(analysis_h * w / h / 2) * 2
    # decode at low fps, RGB for MediaPipe
    fps = 5  # analysis fps
    cmd = [
        "ffmpeg", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{dur:.3f}", "-i", src,
        "-vf", f"scale={analysis_w}:{analysis_h}",
        "-r", str(fps),
        "-f", "rawvideo", "-pix_fmt", "rgb24", "-",
    ]
    try:
        raw = run_ffmpeg(cmd, timeout=600).stdout
    except Exception:
        return []
    frame_bytes = analysis_w * analysis_h * 3
    n_frames = len(raw) // frame_bytes
    if n_frames < 4:
        return []

    frames = np.frombuffer(raw[: n_frames * frame_bytes], dtype=np.uint8).reshape(
        n_frames, analysis_h, analysis_w, 3
    )

    traj_scaled: list[float] = []
    for i in range(n_frames):
        frame_rgb = frames[i]
        # MediaPipe expects RGB
        results = _face_detector.process(frame_rgb)
        if results.detections:
            # take the largest face (by box area)
            best = max(results.detections, key=lambda d:
                d.location_data.relative_bounding_box.width *
                d.location_data.relative_bounding_box.height)
            bbox = best.location_data.relative_bounding_box
            center_x = (bbox.xmin + bbox.width / 2) * analysis_w
        else:
            # no face -> use previous or center
            center_x = traj_scaled[-1] if traj_scaled else analysis_w / 2
        traj_scaled.append(center_x)

    # convert to source pixel scale and smooth with camera physics
    scale = w / analysis_w
    crop_w = min(int(h * ASPECT), w)
    cam_x = w / 2
    target = w / 2
    trajectory: list[float] = []
    for tc in traj_scaled:
        target_scaled = tc * scale
        if abs(target_scaled - target) > crop_w * SAFE_ZONE_FRACTION:
            target = target_scaled
        cam_x = smooth_camera(cam_x, target, crop_w, w)
        trajectory.append(cam_x)
    return trajectory


def build_sendcmd_file(trajectory: list[float], src_w: int, src_h: int,
                       out_fps: float = 30.0, analysis_fps: float = 5.0,
                       cuts: Optional[list[int]] = None) -> str:
    """File sendcmd untuk crop dinamis mengikuti trajektori.

    Trajektori dihitung pada `analysis_fps` (5 fps). Kalau perintah crop hanya
    ditulis 5x per detik, gerakan kamera terlihat PATAH-PATAH (melompat tiap
    200 ms). Karena itu di sini trajektori di-INTERPOLASI ke `out_fps` supaya
    perintah keluar tiap ~33 ms → gerakan mulus.

    cuts = indeks frame analisis tempat pembicara BERGANTI. Di titik itu
    interpolasi TIDAK dilakukan (posisi melompat seketika = teleport).
    """
    crop_w = min(int(src_h * ASPECT), src_w)
    cut_set = set(cuts or [])
    max_x = max(0, src_w - crop_w)
    step = max(1.0, out_fps) / max(1.0, analysis_fps)   # frame keluar per titik
    lines: list[str] = []
    last_written: Optional[int] = None

    def emit(t: float, cx: float, force: bool = False) -> None:
        nonlocal last_written
        x = max(0, min(max_x, int(round(cx - crop_w / 2))))
        if not force and last_written is not None and x == last_written:
            return                      # hemat: jangan tulis nilai yang sama
        lines.append(f"{t:.3f} crop x {x};")
        last_written = x

    n = len(trajectory)
    for i in range(n):
        t_i = i / analysis_fps
        cx_i = trajectory[i]
        if i in cut_set:
            # teleport: tegaskan posisi tepat di detik itu, tanpa interpolasi
            emit(t_i, cx_i, force=True)
            continue
        emit(t_i, cx_i)
        if i + 1 < n and (i + 1) not in cut_set:
            cx_next = trajectory[i + 1]
            # sisipkan titik antara supaya pergerakan mulus
            sub = int(step)
            for k in range(1, sub):
                f = k / step
                emit(t_i + (k / max(1.0, out_fps)),
                     cx_i + (cx_next - cx_i) * f)
    fd, path = tempfile.mkstemp(suffix=".cmd", prefix="cam_")
    with os.fdopen(fd, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


# ---------------------------------------------------------------------------
# Clip render
# ---------------------------------------------------------------------------

def render_clip(
    src: str,
    start: float,
    end: float,
    ass_path: Optional[str],
    out_path: str,
    resolution: str = "1080x1920",
    face_tracking: bool = True,
    camera_trajectory: Optional[list[float]] = None,
    camera_cuts: Optional[list[int]] = None,
    watermark: bool = True,
    icon_ass_path: Optional[str] = None,
    icon_png_overlays: Optional[list[dict[str, Any]]] = None,
    broll_video_overlays: Optional[list[dict[str, Any]]] = None,
) -> str:
    """Cut + reframe + burn subtitles (+ ikon overlay) -> vertical MP4.

    Resolution choices: 1080x1920, 720x1280, 1080x1080.
    watermark: bakar watermark CortexClipAI (default ON — dihapus hanya
    setelah user menonton 4 iklan, via flag dari render_clip.py).
    icon_ass_path: ASS overlay ikon/b-roll (layer terpisah dari subtitle).
    """
    w, h = map(int, resolution.split("x"))
    aspect = w / h
    src_w, src_h = probe_size(src)

    # watermark PNG komposit (logo+nama+tagline) — skala ke lebar output
    wm_path = None
    if watermark:
        try:
            from .watermark import build_watermark_png
            wm_path = build_watermark_png(target_width=w)
        except Exception:
            wm_path = None

    # already vertical-ish? pass through crop centered
    filters: list[str] = []
    vf_parts: list[str] = []

    if face_tracking and camera_trajectory and len(camera_trajectory) > 1:
        cmdfile = build_sendcmd_file(camera_trajectory, src_w, src_h,
                                     cuts=camera_cuts)
        crop_w = min(int(src_h * aspect), src_w)
        # dynamic crop with sendcmd-driven x
        vf_parts.append(f"sendcmd=f={cmdfile}")
        vf_parts.append(f"crop=w={crop_w}:h={src_h}:x=0:y=0")
    else:
        # center crop to target aspect
        if src_w / src_h > aspect:
            crop_w = int(src_h * aspect)
            vf_parts.append(f"crop=w={crop_w}:h={src_h}:x=(iw-ow)/2:y=0")
        else:
            crop_h = int(src_w / aspect)
            vf_parts.append(f"crop=w={src_w}:h={crop_h}:x=0:y=(ih-oh)/2")

    # scale to delivery size (never downscale below source quality needlessly)
    vf_parts.append(f"scale={w}:{h}:force_original_aspect_ratio=increase")
    vf_parts.append(f"crop={w}:{h}")

    from .subtitles import fonts_dir as subtitle_fonts_dir
    fonts_dir = subtitle_fonts_dir()

    def ass_filter(p: str) -> str:
        esc = p.replace("\\", "/").replace(":", "\\:").replace("'", "\\'")
        return f"ass='{esc}':fontsdir='{fonts_dir}'"

    if ass_path:
        vf_parts.append(ass_filter(ass_path))
    if icon_ass_path:
        vf_parts.append(ass_filter(icon_ass_path))

    # --- ikon & b-roll: overlay PNG per placement (Twemoji pre-render) ---
    # ASS emoji tidak andal (libass+CBDT/COLRv1 blank di beberapa build);
    # PNG overlay 100% konsisten antar mesin.
    png_overlays: list[dict[str, Any]] = []
    if icon_png_overlays:
        png_overlays = icon_png_overlays

    # --- watermark overlay (kiri-atas, offset dari pojok biar terbaca) ---
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{end - start:.3f}", "-i", src,
    ]

    # bangun filter_complex bertingkat: [vbase] → overlay PNG → watermark → [vout]
    fc_parts: list[str] = []
    cur = "0:v"
    fc_head = f"{','.join(vf_parts)}" if vf_parts else "null"
    fc_parts.append(f"[{cur}]{fc_head}[vbase]")
    cur = "vbase"
    input_idx = 1
    clip_dur = max(0.2, float(end) - float(start))

    # --- B-ROLL VIDEO: PiP di atas video utama (mirror preview <video> PiP) ---
    # Muncul di jendela membulat area atas; audio b-roll dibuang (hanya visual).
    for bv in (broll_video_overlays or []):
        path = bv.get("file")
        if not path or not os.path.exists(path):
            continue
        ts = max(0.0, float(bv.get("t_start", 0)))
        te = min(clip_dur, float(bv.get("t_end", ts + 2.5)))
        if te - ts < 0.3:
            continue
        bw = int(bv.get("width", int(w * 0.78)))
        bh = int(bv.get("height", int(bw * 9 / 16)))
        bx = int(bv.get("x", (w - bw) // 2))
        by = int(bv.get("y", int(h * 0.14)))
        fade_d = min(0.3, max(0.1, (te - ts) / 4.0))
        # loop b-roll biar cukup panjang, mulai dari 0, dipotong ke durasi tampil
        cmd += ["-stream_loop", "-1", "-t", f"{te - ts:.3f}", "-i", path]
        fc_parts.append(
            f"[{input_idx}:v]scale={bw}:{bh}:force_original_aspect_ratio=increase,"
            f"crop={bw}:{bh},setsar=1,format=rgba,"
            f"fade=t=in:st=0:d={fade_d:.2f}:alpha=1,"
            f"fade=t=out:st={max(0.0, (te - ts) - fade_d):.2f}:d={fade_d:.2f}:alpha=1,"
            f"setpts=PTS-STARTPTS+{ts:.3f}/TB[brl{input_idx}]"
        )
        fc_parts.append(
            f"[{cur}][brl{input_idx}]overlay=x={bx}:y={by}:"
            f"eof_action=pass:enable='between(t,{ts:.2f},{te:.2f})'[vb{input_idx}]"
        )
        cur = f"vb{input_idx}"
        input_idx += 1

    # ikon & b-roll PNG: fade in/out + slide masuk (mirror transisi CSS preview).
    # x/y dari caller = TITIK TENGAH ikon (mirror translate(-50%,-50%) preview).
    for ov in png_overlays:
        size = int(ov.get("size", int(w * 0.20)))
        cx = int(ov.get("x", int(w * 0.62)))
        cy = int(ov.get("y", int(h * 0.30)))
        px = cx - size // 2
        py = cy - size // 2
        ts = max(0.0, float(ov.get("t_start", 0)))
        te = min(clip_dur, float(ov.get("t_end", ts + 2.5)))
        if te <= ts:
            continue
        fade_d = min(0.28, max(0.08, (te - ts) / 3.0))
        fade_out_st = max(ts + 0.02, te - fade_d)
        # -loop 1 -t: PNG jadi stream berdurasi klip → filter fade (timeline) jalan
        cmd += ["-loop", "1", "-t", f"{clip_dur:.3f}", "-i", ov["png"]]
        fc_parts.append(
            f"[{input_idx}:v]scale={size}:-1,format=rgba,"
            f"fade=t=in:st={ts:.2f}:d={fade_d:.2f}:alpha=1,"
            f"fade=t=out:st={fade_out_st:.2f}:d={fade_d:.2f}:alpha=1[ico{input_idx}]"
        )
        # slide masuk 0.35s: posisi awal offset → posisi final (ease linear)
        anim = str(ov.get("anim") or "")
        xe, ye = str(px), str(py)
        if anim in ("slide-left", "slide-right", "slide-up", "slide-down"):
            k = f"max(0,1-(t-{ts:.2f})/0.35)"
            dist = int(w * 0.35)
            if anim == "slide-left":
                xe = f"'{px}+{dist}*{k}'"
            elif anim == "slide-right":
                xe = f"'{px}-{dist}*{k}'"
            elif anim == "slide-up":
                ye = f"'{py}+{dist}*{k}'"
            else:
                ye = f"'{py}-{dist}*{k}'"
        fc_parts.append(
            f"[{cur}][ico{input_idx}]overlay=x={xe}:y={ye}:"
            f"enable='between(t,{ts:.2f},{te:.2f})'[vo{input_idx}]"
        )
        cur = f"vo{input_idx}"
        input_idx += 1

    if wm_path:
        x = int(w * 0.055)
        y = int(h * 0.045)
        # 0.30 → 0.52: watermark ~1.7x lebih besar & sekarang setara blok
        # watermark preview editor (logo 9.5% + teks tagline ≈ 50% lebar).
        wm_w = int(w * 0.52)
        cmd += ["-i", wm_path]
        fc_parts.append(f"[{input_idx}:v]scale={wm_w}:-1[wm]")
        fc_parts.append(f"[{cur}][wm]overlay={x}:{y}:format=auto[vout]")
        cmd += ["-filter_complex", ";".join(fc_parts), "-map", "[vout]", "-map", "0:a?"]
    else:
        if png_overlays or (broll_video_overlays or []):
            fc_parts.append(f"[{cur}]null[vout]")
            cmd += ["-filter_complex", ";".join(fc_parts), "-map", "[vout]", "-map", "0:a?"]
        else:
            cmd += ["-vf", ",".join(vf_parts)] if vf_parts else ["-vf", "null"]

    cmd += [
        # threads 2 (VPS 4 core): sisakan core untuk web server — dengan
        # threads=4 ffmpeg menyita seluruh CPU → web lag/blank saat render.
        "-c:v", "libx264", "-preset", "medium", "-crf", "18",
        "-threads", "2",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "128k", "-ar", "44100",
        "-ac", "2",
        "-movflags", "+faststart",
        "-metadata", "comment=Made with CortexClip AI",
        out_path,
    ]
    run_ffmpeg(cmd)
    return out_path


def render_preview_fast(
    src: str,
    start: float,
    end: float,
    out_path: str,
    width: int = 270,
    height: int = 480,
) -> str:
    """Preview KILAT: potong + crop tengah 9:16 + transkode ultrafast.

    Tanpa face tracking, tanpa watermark, tanpa subtitle (browser yang
    menampilkan subtitle live overlay). 270x480 CRF30 audio copy → klip
    60 detik selesai ±3-6 detik di CPU 4 core.
    """
    w, h = width, height
    src_w, src_h = probe_size(src)
    aspect = w / h
    vf_parts: list[str] = []
    if src_w / src_h > aspect:
        crop_w = int(src_h * aspect)
        vf_parts.append(f"crop=w={crop_w}:h={src_h}:x=(iw-ow)/2:y=0")
    else:
        crop_h = int(src_w / aspect)
        vf_parts.append(f"crop=w={src_w}:h={crop_h}:x=0:y=(ih-oh)/2")
    vf_parts.append(f"scale={w}:{h}")

    pre: list[str] = ["ffmpeg", "-y", "-v", "error"]
    # sumber HTTP (video besar di storage): jangan mati karena putus sesaat,
    # dan seek pakai HTTP Range supaya tidak menarik seluruh file
    if src.startswith("http"):
        pre += ["-reconnect", "1", "-reconnect_streamed", "1",
                "-reconnect_delay_max", "5", "-rw_timeout", "30000000"]

    cmd = pre + [
        "-ss", f"{start:.3f}", "-t", f"{end - start:.3f}", "-i", src,
        "-vf", ",".join(vf_parts),
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "30",
        # VPS 4 core: sisakan CPU untuk web server (bukan 4 = web jadi blank)
        "-threads", "2",
        "-pix_fmt", "yuv420p",
        # coba copy audio (instan); kalau codec tak kompatibel ffmpeg error → caller retry
        "-c:a", "aac", "-b:a", "96k",
        "-movflags", "+faststart",
        out_path,
    ]
    run_ffmpeg(cmd, timeout=600)
    return out_path




def burn_hook_overlay(
    src: str,
    hook_text: str,
    out_path: str,
    position: str = "top",
    fontsize_ratio: float = 0.055,
) -> str:
    """Burn AI-generated hook text onto video using ffmpeg drawtext.
    
    Args:
        src: input video path
        hook_text: hook text to burn
        out_path: output video path
        position: "top" or "bottom"
        fontsize_ratio: font size as fraction of video height
    """
    if not hook_text or not hook_text.strip():
        shutil.copy2(src, out_path)
        return out_path
    
    # Escape special chars for drawtext
    escaped = hook_text.replace("\\", "\\\\") \
                       .replace(":", "\\:") \
                       .replace("'", "\\'") \
                       .replace("%", "\\%") \
                       .replace(",", "\\,") \
                       .replace("[", "\\[") \
                       .replace("]", "\\]")
    
    x = "(w-text_w)/2"
    y = "h*0.06" if position == "top" else "h-text_h-h*0.04"
    
    drawtext = (
        f"drawtext=text='{escaped}':x={x}:y={y}:"
        f"fontsize=h*{fontsize_ratio}:"
        f"fontcolor=white:borderw=4:bordercolor=black:"
        f"fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    )
    
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-i", src,
        "-vf", drawtext,
        "-c:a", "copy",
        "-c:v", "libx264", "-preset", "medium", "-crf", "18",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        out_path,
    ]
    run_ffmpeg(cmd)
    return out_path

def render_clip_webm_style(
    src: str, start: float, end: float, out_path: str
) -> str:
    """Quick cut without subtitles (for preview or fast drafts)."""
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{end - start:.3f}", "-i", src,
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "23",
        "-c:a", "aac", "-b:a", "128k",
        out_path,
    ]
    run_ffmpeg(cmd)
    return out_path
