"""FFmpeg render engine — burns the SAME ASS file the browser preview uses.

Parity guarantee (user requirement: preview == MP4 result):
  preview  : browser canvas renders words+style with rules mirroring libass
  render   : ffmpeg -vf ass=captions.ass on a 1080x1920 canvas
The ASS file is generated by app/subtitles.py from the same CaptionStyle JSON
the frontend sends, so parameters cannot drift between preview and result.

Face tracking (port sederhana dari OpenShorts TRACK mode):
  - Analisis pass di Python: sampling frame tiap N frame di resolusi rendah,
    deteksi posisi "subject" via deteksi gerak + deteksi wajah sederhana
    (gradient-based Viola-Jones via OpenCV kalau tersedia; fallback: centroid
    gerak). Kamera virtual smooth (safe-zone + pan speed) seperti
    SmoothedCameraman OpenShorts.
  - Render pass: crop dinamis via ffmpeg sendcmd + crop filter.
"""

from __future__ import annotations

import os
import json
import shutil
import subprocess
import tempfile
from typing import Any, Optional

import numpy as np
import cv2
import mediapipe as mp

ASPECT = 9 / 16
ANALYSIS_WIDTH = 320          # low-res analysis pass
DETECT_STRIDE = 5             # analyze every Nth frame
SAFE_ZONE_FRACTION = 0.22
PAN_SPEED_FAST = 18.0
PAN_SPEED_SLOW = 4.0

# MediaPipe BlazeFace setup (OpenShorts style) - legacy API (mediapipe 0.10)
mp_face_detection = mp.solutions.face_detection
_face_detector = mp_face_detection.FaceDetection(model_selection=1, min_detection_confidence=0.5)


def probe_duration(path: str) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "json", path],
        capture_output=True, text=True, check=True,
    ).stdout
    return float(json.loads(out)["format"]["duration"])


def probe_size(path: str) -> tuple[int, int]:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=width,height", "-of", "json", path],
        capture_output=True, text=True, check=True,
    ).stdout
    data = json.loads(out)["streams"][0]
    return int(data["width"]), int(data["height"])


# ---------------------------------------------------------------------------
# Camera trajectory (SmoothedCameraman port)
# ---------------------------------------------------------------------------

def smooth_camera(
    current: float, target: float, crop_width: float, video_width: float,
    fast: float = PAN_SPEED_FAST, slow: float = PAN_SPEED_SLOW,
) -> float:
    diff = target - current
    safe = crop_width * SAFE_ZONE_FRACTION
    if abs(diff) <= safe:
        return current
    direction = 1.0 if diff > 0 else -1.0
    speed = fast if abs(diff) > crop_width * 0.5 else slow
    new = current + direction * speed
    half = crop_width / 2
    new = max(half, min(video_width - half, new))
    new_diff = target - new
    if (direction == 1 and new_diff < 0) or (direction == -1 and new_diff > 0):
        new = target
    return new


def analyze_face_track(src: str, start: float, end: float) -> list[float]:
    """Analyze the clip for a per-frame camera-center trajectory (x in source px).

    Uses MediaPipe BlazeFace (like OpenShorts TRACK mode) for robust face detection
    at low resolution. Falls back to center if no faces detected.
    """
    import numpy as np
    try:
        w, h = probe_size(src)
    except Exception:
        return []
    dur = min(end - start, 120)  # cap analysis length
    analysis_h = max(180, int(ANALYSIS_WIDTH * h / w / 2) * 2)
    analysis_w = int(analysis_h * w / h / 2) * 2
    # decode at low fps, RGB for MediaPipe
    fps = 5  # analysis fps
    cmd = [
        "ffmpeg", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{dur:.3f}", "-i", src,
        "-vf", f"scale={analysis_w}:{analysis_h}",
        "-r", str(fps),
        "-f", "rawvideo", "-pix_fmt", "rgb24", "-",
    ]
    try:
        raw = subprocess.run(cmd, capture_output=True, check=True, timeout=600).stdout
    except Exception:
        return []
    frame_bytes = analysis_w * analysis_h * 3
    n_frames = len(raw) // frame_bytes
    if n_frames < 4:
        return []

    frames = np.frombuffer(raw[: n_frames * frame_bytes], dtype=np.uint8).reshape(
        n_frames, analysis_h, analysis_w, 3
    )

    traj_scaled: list[float] = []
    for i in range(n_frames):
        frame_rgb = frames[i]
        # MediaPipe expects RGB
        results = _face_detector.process(frame_rgb)
        if results.detections:
            # take the largest face (by box area)
            best = max(results.detections, key=lambda d: 
                d.location_data.relative_bounding_box.width * 
                d.location_data.relative_bounding_box.height)
            bbox = best.location_data.relative_bounding_box
            center_x = (bbox.xmin + bbox.width / 2) * analysis_w
        else:
            # no face -> use previous or center
            center_x = traj_scaled[-1] if traj_scaled else analysis_w / 2
        traj_scaled.append(center_x)

    # convert to source pixel scale and smooth with camera physics
    scale = w / analysis_w
    crop_w = min(int(h * ASPECT), w)
    cam_x = w / 2
    target = w / 2
    trajectory: list[float] = []
    for tc in traj_scaled:
        target_scaled = tc * scale
        if abs(target_scaled - target) > crop_w * SAFE_ZONE_FRACTION:
            target = target_scaled
        cam_x = smooth_camera(cam_x, target, crop_w, w)
        trajectory.append(cam_x)
    return trajectory


def build_sendcmd_file(trajectory: list[float], src_w: int, src_h: int, out_fps: float = 30.0, analysis_fps: float = 5.0) -> str:
    """Generate ffmpeg sendcmd file for dynamic crop following trajectory."""
    crop_w = min(int(src_h * ASPECT), src_w)
    lines = []
    for i, cx in enumerate(trajectory):
        t = i / analysis_fps
        x = max(0, min(src_w - crop_w, int(round(cx - crop_w / 2))))
        # set crop x over a short interval for smoothness
        lines.append(f"{t:.3f} crop x {x};")
    fd, path = tempfile.mkstemp(suffix=".cmd", prefix="cam_")
    with os.fdopen(fd, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


# ---------------------------------------------------------------------------
# Clip render
# ---------------------------------------------------------------------------

def render_clip(
    src: str,
    start: float,
    end: float,
    ass_path: Optional[str],
    out_path: str,
    resolution: str = "1080x1920",
    face_tracking: bool = True,
    camera_trajectory: Optional[list[float]] = None,
) -> str:
    """Cut + reframe + burn subtitles -> vertical MP4.

    Resolution choices: 1080x1920, 720x1280, 1080x1080.
    """
    w, h = map(int, resolution.split("x"))
    aspect = w / h
    src_w, src_h = probe_size(src)

    # already vertical-ish? pass through crop centered
    filters: list[str] = []
    vf_parts: list[str] = []

    if face_tracking and camera_trajectory and len(camera_trajectory) > 1:
        cmdfile = build_sendcmd_file(camera_trajectory, src_w, src_h)
        crop_w = min(int(src_h * aspect), src_w)
        # dynamic crop with sendcmd-driven x
        vf_parts.append(f"sendcmd=f={cmdfile}")
        vf_parts.append(f"crop=w={crop_w}:h={src_h}:x=0:y=0")
    else:
        # center crop to target aspect
        if src_w / src_h > aspect:
            crop_w = int(src_h * aspect)
            vf_parts.append(f"crop=w={crop_w}:h={src_h}:x=(iw-ow)/2:y=0")
        else:
            crop_h = int(src_w / aspect)
            vf_parts.append(f"crop=w={src_w}:h={crop_h}:x=0:y=(ih-oh)/2")

    # scale to delivery size (never downscale below source quality needlessly)
    vf_parts.append(f"scale={w}:{h}:force_original_aspect_ratio=increase")
    vf_parts.append(f"crop={w}:{h}")
    if ass_path:
        # escape path for filter
        esc = ass_path.replace("\\", "/").replace(":", "\\:").replace("'", "\\'")
        vf_parts.append(f"ass='{esc}'")

    vf = ",".join(vf_parts)
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{end - start:.3f}", "-i", src,
        "-vf", vf,
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "128k",
        "-movflags", "+faststart",
        "-metadata", "comment=Made with CortexClip AI",
        out_path,
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    return out_path




def burn_hook_overlay(
    src: str,
    hook_text: str,
    out_path: str,
    position: str = "top",
    fontsize_ratio: float = 0.055,
) -> str:
    """Burn AI-generated hook text onto video using ffmpeg drawtext.
    
    Args:
        src: input video path
        hook_text: hook text to burn
        out_path: output video path
        position: "top" or "bottom"
        fontsize_ratio: font size as fraction of video height
    """
    if not hook_text or not hook_text.strip():
        shutil.copy2(src, out_path)
        return out_path
    
    # Escape special chars for drawtext
    escaped = hook_text.replace("\\", "\\\\") \
                       .replace(":", "\\:") \
                       .replace("'", "\\'") \
                       .replace("%", "\\%") \
                       .replace(",", "\\,") \
                       .replace("[", "\\[") \
                       .replace("]", "\\]")
    
    x = "(w-text_w)/2"
    y = "h*0.06" if position == "top" else "h-text_h-h*0.04"
    
    drawtext = (
        f"drawtext=text='{escaped}':x={x}:y={y}:"
        f"fontsize=h*{fontsize_ratio}:"
        f"fontcolor=white:borderw=4:bordercolor=black:"
        f"fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    )
    
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-i", src,
        "-vf", drawtext,
        "-c:a", "copy",
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        out_path,
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    return out_path

def render_clip_webm_style(
    src: str, start: float, end: float, out_path: str
) -> str:
    """Quick cut without subtitles (for preview or fast drafts)."""
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-ss", f"{start:.3f}", "-t", f"{end - start:.3f}", "-i", src,
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "23",
        "-c:a", "aac", "-b:a", "128k",
        out_path,
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    return out_path
