/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedUnduhRouteImport } from './routes/_authenticated/unduh'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedEditorClipIdRouteImport } from './routes/_authenticated/editor.$clipId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnduhRoute = AuthenticatedUnduhRouteImport.update({
  id: '/unduh',
  path: '/unduh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorClipIdRoute =
  AuthenticatedEditorClipIdRouteImport.update({
    id: '/editor/$clipId',
    path: '/editor/$clipId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/unduh': typeof AuthenticatedUnduhRoute
  '/share/$token': typeof ShareTokenRoute
  '/editor/$clipId': typeof AuthenticatedEditorClipIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/unduh': typeof AuthenticatedUnduhRoute
  '/share/$token': typeof ShareTokenRoute
  '/editor/$clipId': typeof AuthenticatedEditorClipIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/unduh': typeof AuthenticatedUnduhRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/editor/$clipId': typeof AuthenticatedEditorClipIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/reset-password'
    | '/studio'
    | '/dashboard'
    | '/pengaturan'
    | '/unduh'
    | '/share/$token'
    | '/editor/$clipId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/reset-password'
    | '/studio'
    | '/dashboard'
    | '/pengaturan'
    | '/unduh'
    | '/share/$token'
    | '/editor/$clipId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/reset-password'
    | '/studio'
    | '/_authenticated/dashboard'
    | '/_authenticated/pengaturan'
    | '/_authenticated/unduh'
    | '/share/$token'
    | '/_authenticated/editor/$clipId'
    | '/_authenticated/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudioRoute: typeof StudioRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unduh': {
      id: '/_authenticated/unduh'
      path: '/unduh'
      fullPath: '/unduh'
      preLoaderRoute: typeof AuthenticatedUnduhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$clipId': {
      id: '/_authenticated/editor/$clipId'
      path: '/editor/$clipId'
      fullPath: '/editor/$clipId'
      preLoaderRoute: typeof AuthenticatedEditorClipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedUnduhRoute: typeof AuthenticatedUnduhRoute
  AuthenticatedEditorClipIdRoute: typeof AuthenticatedEditorClipIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedUnduhRoute: AuthenticatedUnduhRoute,
  AuthenticatedEditorClipIdRoute: AuthenticatedEditorClipIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudioRoute: StudioRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
