/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedUnduhRouteImport } from './routes/_authenticated/unduh'
import { Route as AdminLogRouteImport } from './routes/admin.log'
import { Route as DocsBatasRouteImport } from './routes/docs/batas'
import { Route as DocsCustomLogoRouteImport } from './routes/docs/custom-logo'
import { Route as DocsEditorRouteImport } from './routes/docs/editor'
import { Route as DocsHargaRouteImport } from './routes/docs/harga'
import { Route as DocsKeamananRouteImport } from './routes/docs/keamanan'
import { Route as DocsManualTrackingRouteImport } from './routes/docs/manual-tracking'
import { Route as DocsMasalahRouteImport } from './routes/docs/masalah'
import { Route as DocsMonetisasiVideoPendekRouteImport } from './routes/docs/monetisasi-video-pendek'
import { Route as DocsMulaiCepatRouteImport } from './routes/docs/mulai-cepat'
import { Route as DocsOptimasiKaraokeSubtitleRouteImport } from './routes/docs/optimasi-karaoke-subtitle'
import { Route as DocsPanduanKontenViralRouteImport } from './routes/docs/panduan-konten-viral'
import { Route as DocsWhatIsCortexclipaiRouteImport } from './routes/docs/what-is-cortexclipai'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedEditorClipIdRouteImport } from './routes/_authenticated/editor.$clipId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AdminLogSystemaiRouteImport } from './routes/admin.log.systemai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnduhRoute = AuthenticatedUnduhRouteImport.update({
  id: '/unduh',
  path: '/unduh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRoute,
} as any)
const DocsBatasRoute = DocsBatasRouteImport.update({
  id: '/batas',
  path: '/batas',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomLogoRoute = DocsCustomLogoRouteImport.update({
  id: '/custom-logo',
  path: '/custom-logo',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEditorRoute = DocsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHargaRoute = DocsHargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => DocsRoute,
} as any)
const DocsKeamananRoute = DocsKeamananRouteImport.update({
  id: '/keamanan',
  path: '/keamanan',
  getParentRoute: () => DocsRoute,
} as any)
const DocsManualTrackingRoute = DocsManualTrackingRouteImport.update({
  id: '/manual-tracking',
  path: '/manual-tracking',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMasalahRoute = DocsMasalahRouteImport.update({
  id: '/masalah',
  path: '/masalah',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMonetisasiVideoPendekRoute =
  DocsMonetisasiVideoPendekRouteImport.update({
    id: '/monetisasi-video-pendek',
    path: '/monetisasi-video-pendek',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsMulaiCepatRoute = DocsMulaiCepatRouteImport.update({
  id: '/mulai-cepat',
  path: '/mulai-cepat',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOptimasiKaraokeSubtitleRoute =
  DocsOptimasiKaraokeSubtitleRouteImport.update({
    id: '/optimasi-karaoke-subtitle',
    path: '/optimasi-karaoke-subtitle',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPanduanKontenViralRoute = DocsPanduanKontenViralRouteImport.update({
  id: '/panduan-konten-viral',
  path: '/panduan-konten-viral',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWhatIsCortexclipaiRoute = DocsWhatIsCortexclipaiRouteImport.update({
  id: '/what-is-cortexclipai',
  path: '/what-is-cortexclipai',
  getParentRoute: () => DocsRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorClipIdRoute =
  AuthenticatedEditorClipIdRouteImport.update({
    id: '/editor/$clipId',
    path: '/editor/$clipId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminLogSystemaiRoute = AdminLogSystemaiRouteImport.update({
  id: '/systemai',
  path: '/systemai',
  getParentRoute: () => AdminLogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRouteWithChildren
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/unduh': typeof AuthenticatedUnduhRoute
  '/admin/log': typeof AdminLogRouteWithChildren
  '/docs/batas': typeof DocsBatasRoute
  '/docs/custom-logo': typeof DocsCustomLogoRoute
  '/docs/editor': typeof DocsEditorRoute
  '/docs/harga': typeof DocsHargaRoute
  '/docs/keamanan': typeof DocsKeamananRoute
  '/docs/manual-tracking': typeof DocsManualTrackingRoute
  '/docs/masalah': typeof DocsMasalahRoute
  '/docs/monetisasi-video-pendek': typeof DocsMonetisasiVideoPendekRoute
  '/docs/mulai-cepat': typeof DocsMulaiCepatRoute
  '/docs/optimasi-karaoke-subtitle': typeof DocsOptimasiKaraokeSubtitleRoute
  '/docs/panduan-konten-viral': typeof DocsPanduanKontenViralRoute
  '/docs/what-is-cortexclipai': typeof DocsWhatIsCortexclipaiRoute
  '/share/$token': typeof ShareTokenRoute
  '/editor/$clipId': typeof AuthenticatedEditorClipIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/admin/log/systemai': typeof AdminLogSystemaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRouteWithChildren
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/unduh': typeof AuthenticatedUnduhRoute
  '/admin/log': typeof AdminLogRouteWithChildren
  '/docs/batas': typeof DocsBatasRoute
  '/docs/custom-logo': typeof DocsCustomLogoRoute
  '/docs/editor': typeof DocsEditorRoute
  '/docs/harga': typeof DocsHargaRoute
  '/docs/keamanan': typeof DocsKeamananRoute
  '/docs/manual-tracking': typeof DocsManualTrackingRoute
  '/docs/masalah': typeof DocsMasalahRoute
  '/docs/monetisasi-video-pendek': typeof DocsMonetisasiVideoPendekRoute
  '/docs/mulai-cepat': typeof DocsMulaiCepatRoute
  '/docs/optimasi-karaoke-subtitle': typeof DocsOptimasiKaraokeSubtitleRoute
  '/docs/panduan-konten-viral': typeof DocsPanduanKontenViralRoute
  '/docs/what-is-cortexclipai': typeof DocsWhatIsCortexclipaiRoute
  '/share/$token': typeof ShareTokenRoute
  '/editor/$clipId': typeof AuthenticatedEditorClipIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/admin/log/systemai': typeof AdminLogSystemaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRouteWithChildren
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/unduh': typeof AuthenticatedUnduhRoute
  '/admin/log': typeof AdminLogRouteWithChildren
  '/docs/batas': typeof DocsBatasRoute
  '/docs/custom-logo': typeof DocsCustomLogoRoute
  '/docs/editor': typeof DocsEditorRoute
  '/docs/harga': typeof DocsHargaRoute
  '/docs/keamanan': typeof DocsKeamananRoute
  '/docs/manual-tracking': typeof DocsManualTrackingRoute
  '/docs/masalah': typeof DocsMasalahRoute
  '/docs/monetisasi-video-pendek': typeof DocsMonetisasiVideoPendekRoute
  '/docs/mulai-cepat': typeof DocsMulaiCepatRoute
  '/docs/optimasi-karaoke-subtitle': typeof DocsOptimasiKaraokeSubtitleRoute
  '/docs/panduan-konten-viral': typeof DocsPanduanKontenViralRoute
  '/docs/what-is-cortexclipai': typeof DocsWhatIsCortexclipaiRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/editor/$clipId': typeof AuthenticatedEditorClipIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/admin/log/systemai': typeof AdminLogSystemaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/reset-password'
    | '/studio'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/dashboard'
    | '/pengaturan'
    | '/unduh'
    | '/admin/log'
    | '/docs/batas'
    | '/docs/custom-logo'
    | '/docs/editor'
    | '/docs/harga'
    | '/docs/keamanan'
    | '/docs/manual-tracking'
    | '/docs/masalah'
    | '/docs/monetisasi-video-pendek'
    | '/docs/mulai-cepat'
    | '/docs/optimasi-karaoke-subtitle'
    | '/docs/panduan-konten-viral'
    | '/docs/what-is-cortexclipai'
    | '/share/$token'
    | '/editor/$clipId'
    | '/projects/$projectId'
    | '/admin/log/systemai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/reset-password'
    | '/studio'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/dashboard'
    | '/pengaturan'
    | '/unduh'
    | '/admin/log'
    | '/docs/batas'
    | '/docs/custom-logo'
    | '/docs/editor'
    | '/docs/harga'
    | '/docs/keamanan'
    | '/docs/manual-tracking'
    | '/docs/masalah'
    | '/docs/monetisasi-video-pendek'
    | '/docs/mulai-cepat'
    | '/docs/optimasi-karaoke-subtitle'
    | '/docs/panduan-konten-viral'
    | '/docs/what-is-cortexclipai'
    | '/share/$token'
    | '/editor/$clipId'
    | '/projects/$projectId'
    | '/admin/log/systemai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/reset-password'
    | '/studio'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/_authenticated/dashboard'
    | '/_authenticated/pengaturan'
    | '/_authenticated/unduh'
    | '/admin/log'
    | '/docs/batas'
    | '/docs/custom-logo'
    | '/docs/editor'
    | '/docs/harga'
    | '/docs/keamanan'
    | '/docs/manual-tracking'
    | '/docs/masalah'
    | '/docs/monetisasi-video-pendek'
    | '/docs/mulai-cepat'
    | '/docs/optimasi-karaoke-subtitle'
    | '/docs/panduan-konten-viral'
    | '/docs/what-is-cortexclipai'
    | '/share/$token'
    | '/_authenticated/editor/$clipId'
    | '/_authenticated/projects/$projectId'
    | '/admin/log/systemai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRouteWithChildren
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KontakRoute: typeof KontakRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudioRoute: typeof StudioRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TentangKamiRoute: typeof TentangKamiRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unduh': {
      id: '/_authenticated/unduh'
      path: '/unduh'
      fullPath: '/unduh'
      preLoaderRoute: typeof AuthenticatedUnduhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/batas': {
      id: '/docs/batas'
      path: '/batas'
      fullPath: '/docs/batas'
      preLoaderRoute: typeof DocsBatasRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/custom-logo': {
      id: '/docs/custom-logo'
      path: '/custom-logo'
      fullPath: '/docs/custom-logo'
      preLoaderRoute: typeof DocsCustomLogoRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/editor': {
      id: '/docs/editor'
      path: '/editor'
      fullPath: '/docs/editor'
      preLoaderRoute: typeof DocsEditorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/harga': {
      id: '/docs/harga'
      path: '/harga'
      fullPath: '/docs/harga'
      preLoaderRoute: typeof DocsHargaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/keamanan': {
      id: '/docs/keamanan'
      path: '/keamanan'
      fullPath: '/docs/keamanan'
      preLoaderRoute: typeof DocsKeamananRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/manual-tracking': {
      id: '/docs/manual-tracking'
      path: '/manual-tracking'
      fullPath: '/docs/manual-tracking'
      preLoaderRoute: typeof DocsManualTrackingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/masalah': {
      id: '/docs/masalah'
      path: '/masalah'
      fullPath: '/docs/masalah'
      preLoaderRoute: typeof DocsMasalahRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/monetisasi-video-pendek': {
      id: '/docs/monetisasi-video-pendek'
      path: '/monetisasi-video-pendek'
      fullPath: '/docs/monetisasi-video-pendek'
      preLoaderRoute: typeof DocsMonetisasiVideoPendekRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mulai-cepat': {
      id: '/docs/mulai-cepat'
      path: '/mulai-cepat'
      fullPath: '/docs/mulai-cepat'
      preLoaderRoute: typeof DocsMulaiCepatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/optimasi-karaoke-subtitle': {
      id: '/docs/optimasi-karaoke-subtitle'
      path: '/optimasi-karaoke-subtitle'
      fullPath: '/docs/optimasi-karaoke-subtitle'
      preLoaderRoute: typeof DocsOptimasiKaraokeSubtitleRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/panduan-konten-viral': {
      id: '/docs/panduan-konten-viral'
      path: '/panduan-konten-viral'
      fullPath: '/docs/panduan-konten-viral'
      preLoaderRoute: typeof DocsPanduanKontenViralRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/what-is-cortexclipai': {
      id: '/docs/what-is-cortexclipai'
      path: '/what-is-cortexclipai'
      fullPath: '/docs/what-is-cortexclipai'
      preLoaderRoute: typeof DocsWhatIsCortexclipaiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$clipId': {
      id: '/_authenticated/editor/$clipId'
      path: '/editor/$clipId'
      fullPath: '/editor/$clipId'
      preLoaderRoute: typeof AuthenticatedEditorClipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/log/systemai': {
      id: '/admin/log/systemai'
      path: '/systemai'
      fullPath: '/admin/log/systemai'
      preLoaderRoute: typeof AdminLogSystemaiRouteImport
      parentRoute: typeof AdminLogRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedUnduhRoute: typeof AuthenticatedUnduhRoute
  AuthenticatedEditorClipIdRoute: typeof AuthenticatedEditorClipIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedUnduhRoute: AuthenticatedUnduhRoute,
  AuthenticatedEditorClipIdRoute: AuthenticatedEditorClipIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminLogRouteChildren {
  AdminLogSystemaiRoute: typeof AdminLogSystemaiRoute
}

const AdminLogRouteChildren: AdminLogRouteChildren = {
  AdminLogSystemaiRoute: AdminLogSystemaiRoute,
}

const AdminLogRouteWithChildren = AdminLogRoute._addFileChildren(
  AdminLogRouteChildren,
)

interface AdminRouteChildren {
  AdminLogRoute: typeof AdminLogRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLogRoute: AdminLogRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsBatasRoute: typeof DocsBatasRoute
  DocsCustomLogoRoute: typeof DocsCustomLogoRoute
  DocsEditorRoute: typeof DocsEditorRoute
  DocsHargaRoute: typeof DocsHargaRoute
  DocsKeamananRoute: typeof DocsKeamananRoute
  DocsManualTrackingRoute: typeof DocsManualTrackingRoute
  DocsMasalahRoute: typeof DocsMasalahRoute
  DocsMonetisasiVideoPendekRoute: typeof DocsMonetisasiVideoPendekRoute
  DocsMulaiCepatRoute: typeof DocsMulaiCepatRoute
  DocsOptimasiKaraokeSubtitleRoute: typeof DocsOptimasiKaraokeSubtitleRoute
  DocsPanduanKontenViralRoute: typeof DocsPanduanKontenViralRoute
  DocsWhatIsCortexclipaiRoute: typeof DocsWhatIsCortexclipaiRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsBatasRoute: DocsBatasRoute,
  DocsCustomLogoRoute: DocsCustomLogoRoute,
  DocsEditorRoute: DocsEditorRoute,
  DocsHargaRoute: DocsHargaRoute,
  DocsKeamananRoute: DocsKeamananRoute,
  DocsManualTrackingRoute: DocsManualTrackingRoute,
  DocsMasalahRoute: DocsMasalahRoute,
  DocsMonetisasiVideoPendekRoute: DocsMonetisasiVideoPendekRoute,
  DocsMulaiCepatRoute: DocsMulaiCepatRoute,
  DocsOptimasiKaraokeSubtitleRoute: DocsOptimasiKaraokeSubtitleRoute,
  DocsPanduanKontenViralRoute: DocsPanduanKontenViralRoute,
  DocsWhatIsCortexclipaiRoute: DocsWhatIsCortexclipaiRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRouteWithChildren,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KontakRoute: KontakRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudioRoute: StudioRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TentangKamiRoute: TentangKamiRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
